language: python
python:
  - "2.7"
env:
  - DJANGO=1.7 DB=postgres
# command to install dependencies
install: "pip install -r requirements.txt"
services:
  - postgresql
before_script:
  - cp ./imagr_site/imagr_site/settings.py.travis ./imagr_site/imagr_site/settings.py
  - psql -c 'create database test_imagr;' -U postgres
# command to run tests
script: python ./imagr_site/manage.py test imagr