language: python
python:
  - "2.7"
env:
  - DJANGO=1.7 DB=postgres
# command to install dependencies
install: "pip install -r requirements.txt"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U imagr
# command to run tests
script: python ./imagr_site/manage.py test imagr